# AI Review Manager Workflow Configuration
name: AI Review Manager

on:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run AI Review
        uses: ai-review-manager@v4
        with:
          reviewers: 'Deepseek R1, PHI 2, Mistral, Ollama, Qwen'
          standards: 'vault'
