name: Activate Agents and Reshape Repo

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/activate-agents.yml'
      - 'configs/model_manifest.json'

jobs:
  activate-agents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set offline mode
      run: |
        export TRANSFORMERS_OFFLINE=1
        export HF_HUB_OFFLINE=1

    - name: Initialize Submodules
      run: git submodule update --init --recursive || true

    - name: Prepare workspace
      run: mkdir -p models logs scratchpad

    - name: Clone Models from Manifest
      run: |
        if [[ -f configs/model_manifest.json ]]; then
          jq -r '.models[] | "\(.repo) \(.dir)"' configs/model_manifest.json | while read repo dir; do
            if [ ! -d "models/$dir" ]; then
              echo "[FETCH] $repo -> models/$dir"
              git clone "$repo" "models/$dir"
              rm -rf "models/$dir/.git"
            else
              echo "[SKIP] models/$dir already present"
            fi
          done
        else
          echo "[WARN] No model manifest found, using local agent system"
        fi

    - name: Install Python deps
      run: |
        python3 -m pip install --upgrade pip
        pip install torch --index-url https://download.pytorch.org/whl/cpu || true
        pip install transformers accelerate requests || true

    - name: Run Local Agent System
      run: |
        chmod +x agent.sh
        ./agent.sh plan

    - name: Apply Agent Plan
      run: |
        if [[ -f scratch/plan.sh ]]; then
          chmod +x scratch/plan.sh
          bash scratch/plan.sh || echo "Plan execution completed with warnings."
        else
          echo "No agent plan generated"
        fi

    - name: Forensic Log
      run: |
        ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        echo "{ \"ts\": \"$ts\", \"event\": \"agent_run\", \"frontend_files\": \"$(find frontend -name '*.vue' -o -name '*.js' -o -name '*.ts' 2>/dev/null | wc -l)\", \"backend_files\": \"$(find app/src -name '*.kt' -o -name '*.java' 2>/dev/null | wc -l)\" }" >> logs/agent_run.jsonl

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --cached --quiet || git commit -m "Agent-driven repo transformation"
        git push

