name: Agent command router
on:
  issue_comment:
    types: [created]
permissions:
  contents: read
  pull-requests: write
jobs:
  route:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/assimilate')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: fetch-depth: 0
      - name: Re-run assimilation audit for this PR
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
        run: |
          echo "Triggering audit for PR #$PR_NUMBER"
          gh workflow run pr-assimilation-audit.yml -f pr=${PR_NUMBER}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}