name: SAFETY-ENABLED Copilot Policy Audit [NON-DESTRUCTIVE]

on:
  workflow_dispatch:
    inputs:
      audit_mode:
        description: 'Audit mode (always non-destructive)'
        required: true
        default: 'audit_only'
        type: choice
        options:
        - 'audit_only'

permissions:
  contents: read  # SAFETY: Read-only permissions

jobs:
  safety-policy-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Load Safety Policy
      run: |
        echo "[SAFETY AUDIT] Loading Copilot Safety Policy..."
        if [ -f "configs/activation_rules.json" ]; then
          echo "Safety policy found and loaded"
          jq '.copilot_safety_policy' configs/activation_rules.json
        else
          echo "WARNING: No safety policy found"
        fi

    - name: Non-Destructive Repository Audit
      run: |
        echo "[SAFETY AUDIT] Performing non-destructive repository audit..."
        
        # Create forensic log directory
        mkdir -p logs
        ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        
        # Audit potential issues without making changes
        echo "Checking for potential issues..."
        
        # Count files in root (non-destructive)
        root_files=$(find . -maxdepth 1 -type f | wc -l)
        echo "Root directory file count: $root_files"
        
        # Check for backup files (non-destructive)
        backup_count=$(find . -name "*.backup" | wc -l)
        echo "Backup files found: $backup_count"
        
        # Log audit results
        echo "{\"ts\": \"$ts\", \"event\": \"safety_audit\", \"trigger\": \"${{ github.event_name }}\", \"actor\": \"${{ github.actor }}\", \"audit_mode\": \"${{ inputs.audit_mode }}\", \"root_files\": $root_files, \"backup_files\": $backup_count, \"status\": \"audit_complete\"}" >> logs/safety_audit.jsonl
        
        echo "[SAFETY AUDIT] Audit complete - no modifications made to repository"

    - name: Upload Audit Results
      uses: actions/upload-artifact@v4
      with:
        name: safety-audit-results
        path: logs/safety_audit.jsonl
        retention-days: 30