---
name: Copilot Chatbot Memory System

'on':
  push:
    branches: ['**']
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for Copilot to process'
        required: true
        type: string
      memory_action:
        description: 'Memory action to perform'
        required: false
        type: choice
        options:
          - 'store'
          - 'recall'
          - 'clear'
        default: 'store'

# Global Copilot constraint - only one Copilot operation at a time
concurrency:
  group: copilot-operations
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

jobs:
  copilot-chatbot-memory:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Validate Copilot Authority
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          # Allow both Copilot and authorized users for chatbot interactions
          if [["$GITHUB_ACTOR" != "github-actions[bot]" && "$GITHUB_ACTOR" != \
            "spiralgang"]]; then
            echo "⚠️ Chatbot memory access limited to authorized users"
            echo "Current actor: $GITHUB_ACTOR"
            exit 1
          fi
          echo "✅ Chatbot authority validated for: $GITHUB_ACTOR"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "DevUl Army Copilot[bot]"
          git config --global user.email "devul-copilot@noreply.github.com"

      - name: Initialize Persistent Memory
        run: |
          set -euo pipefail

          echo "🧠 DevUl Army Copilot Chatbot Memory System"
          echo "==========================================="

          # Create memory directory if it doesn't exist
          mkdir -p .github/copilot-memory

          # Initialize memory files
          touch .github/copilot-memory/conversations.jsonl
          touch .github/copilot-memory/user-preferences.json
          touch .github/copilot-memory/project-context.json

          # Ensure memory files have proper permissions
          chmod 644 .github/copilot-memory/*.json*

          echo "✅ Persistent memory system initialized"

      - name: Process Upload Trigger
        if: github.event_name == 'push'
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMITTER: ${{ github.event.head_commit.committer.name }}
        run: |
          set -euo pipefail

          echo "📤 Upload detected - Processing trigger..."
          echo "Branch: $BRANCH_NAME"
          echo "Committer: $COMMITTER"
          echo "Message: $COMMIT_MESSAGE"

          # Store upload event in memory
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "{\"timestamp\": >
            \"$TIMESTAMP\", \"event\": \"upload\", \"branch\": \\
              \"$BRANCH_NAME\", \
              \"committer\": \"$COMMITTER\", \"message\": \\
                \"$COMMIT_MESSAGE\", \"type\": \"automatic_trigger\"}" >> .github/copilot-memory/conversations.jsonl

          # Analyze if this is main organization work
          if [["$BRANCH_NAME" == "main" || "$COMMIT_MESSAGE" =~ \
            ^(chore|docs|style|refactor):]]; then
            echo "🏢 Detected organizational/maintenance work"
            echo "main_org_work=true" >> $GITHUB_ENV
          else
            echo "🔧 Detected feature/development work"
            echo "main_org_work=false" >> $GITHUB_ENV
          fi

      - name: Generate Chatbot Response
        env:
          MESSAGE: ${{ github.event.inputs.message || \\
            github.event.head_commit.message || 'Upload processed' }}
          MEMORY_ACTION: ${{ github.event.inputs.memory_action || 'store' }}
          MAIN_ORG_WORK: ${{ env.main_org_work || 'false' }}
        run: |
          set -euo pipefail

          echo "🤖 Generating DevUl Army Copilot response..."

          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Generate contextual response based on message and memory
          if [["$MAIN_ORG_WORK" == "true"]]; then
            RESPONSE="DevUl Army Copilot Acknowledged - Time: >
              $TIMESTAMP - Action: Organizational maintenance detected - \\
                Memory: \
                Stored in persistent flow memory - Message: $MESSAGE - \\
                  Status: Everything looks good! DevUl Army Living Sriracha AGI is ready to assist!"
          else
            RESPONSE="DevUl Army Copilot Response - Time: >
              $TIMESTAMP - Action: Development work processed - Memory: \\
                Enhanced \
                with new context - Message: $MESSAGE - Status: Looking \\
                  good! DevUl Army Living Sriracha AGI is learning and evolving!"
          fi

          echo "$RESPONSE"

          # Store response in memory
          echo "{\"timestamp\": >
            \"$TIMESTAMP\", \"event\": \"chatbot_response\", \"message\": \
                            \"$MESSAGE\", \"response\": $(echo "$RESPONSE" | \
                jq -Rs .), \"memory_action\": \"$MEMORY_ACTION\", \\
                  \"main_org_work\": \"$MAIN_ORG_WORK\"}" >> .github/copilot-memory/conversations.jsonl

          # Update project context
          echo "{\"last_updated\": >
            \"$TIMESTAMP\", \"project_name\": \"DevUl Army — Living Sriracha \
              AGI\", \"capabilities\": [\"persistent_memory\", \\
                \"upload_triggers\", \"chatbot_responses\", \"main_write_requests\", \"living_code_augmentation\"], \"interaction_count\": $(wc -l < .github/copilot-memory/conversations.jsonl), \"status\": \"active\"}" > .github/copilot-memory/project-context.json

          echo "✅ Chatbot response generated and stored in persistent memory"

      - name: Handle Main Write Request
        if: env.main_org_work == 'true' && github.ref_name != 'main'
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          echo "📝 Processing main write request for organizational changes..."

          # Create issue for main write request
          ISSUE_TITLE="Copilot Request: Merge organizational changes to main"
          ISSUE_BODY="DevUl Army Copilot Main Write Request - Created: >
            $(date -u +"%Y-%m-%dT%H:%M:%SZ") - Branch: $BRANCH_NAME - Type: \
              Organizational/Maintenance Changes - The Copilot system has \\
                detected organizational or maintenance changes that should be merged to main. Please review changes and merge when ready."

          # Only create issue if it doesn't already exist
          EXISTING_ISSUES=$(gh issue list --state open --search "Copilot \
            Request: Merge organizational changes" --json number --jq length)

          if [["$EXISTING_ISSUES" -eq 0]]; then
            gh issue create \
              --title "$ISSUE_TITLE" \
              --body "$ISSUE_BODY" \
              --label "copilot-request,main-write,organization"
            echo "✅ Main write request issue created"
          else
            echo "ℹ️ Main write request issue already exists"
          fi

      - name: Commit Memory Updates
        run: |
          set -euo pipefail

          # Check if there are changes to commit
          if git diff --quiet .github/copilot-memory/; then
            echo "ℹ️ No memory changes to commit"
            exit 0
          fi

          echo "💾 Committing persistent memory updates..."

          git add .github/copilot-memory/
          git commit -m "Update DevUl Army Copilot persistent memory - \\
            Enhanced conversation history, \
            updated project context, processed upload triggers, generated \\
              chatbot responses [skip ci]"

          git push origin ${{ github.ref_name }}

          echo "✅ Persistent memory updated and committed"

      - name: Summary Report
        if: always()
        run: |
          echo "📊 DevUl Army Copilot Memory System Summary"
          echo "==========================================="
          echo "Trigger: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Memory Action: ${{ github.event.inputs.memory_action || 'auto' \
            }}"
          echo "Main Org Work: ${{ env.main_org_work || 'false' }}"
          echo "Status: Complete"
          echo ""
          echo "🧠 Persistent memory active and learning!"
          echo "🤖 DevUl Army — Living Sriracha AGI ready for interaction!"
