name: Copilot Idempotent PR Creation

on:
  workflow_dispatch:
  push:
    branches:
      - 'copilot/fix-*'

# Global Copilot constraint - only one Copilot operation at a time
concurrency:
  group: copilot-operations
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  deduplicate-prs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Validate Copilot Authority
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          # Only allow Copilot to create PRs and branches
          if [[ "$GITHUB_ACTOR" != "github-actions[bot]" && "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "❌ Only Copilot can create PRs and branches"
            exit 1
          fi
          echo "✅ Copilot authority validated for PR operations"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Set up Git
        run: |
          git config --global user.name "DevUl Army Copilot[bot]"
          git config --global user.email "devul-copilot@noreply.github.com"

      - name: Intelligent PR management
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
          BASE_BRANCH: main
        run: |
          set -euo pipefail
          
          echo "🤖 Copilot Idempotent PR Creation System"
          echo "🔍 Processing branch: $BRANCH_NAME"

          # Check for existing open PR from this branch to main
          EXISTING_PR_NUMBER=$(gh pr list --state open --head "$BRANCH_NAME" --base "$BASE_BRANCH" --json number --jq '.[0].number // empty')

          if [[ -n "$EXISTING_PR_NUMBER" ]]; then
            echo "🔄 Open PR #$EXISTING_PR_NUMBER already exists for $BRANCH_NAME → $BASE_BRANCH"
            echo "📝 Updating existing PR with latest commits..."
            
            # Push latest commits to branch
            git push origin "$BRANCH_NAME"
            
            # Update PR with intelligent comment
            gh pr comment "$EXISTING_PR_NUMBER" --body "🤖 **DevUl Army Copilot PR Update**

  **Updated:** $(date -u)
  **Branch:** \`$BRANCH_NAME\`
  **Target:** \`$BASE_BRANCH\`

Branch updated by DevUl Army Copilot automation. No duplicate PR created.

**Next Steps:**
- Review the updated changes
- Run any necessary tests
- Merge when ready

_Generated by DevUl Army Copilot Idempotent PR Creation workflow_"
            
            echo "✅ PR #$EXISTING_PR_NUMBER updated successfully"
          else
            echo "📝 No open PR found for $BRANCH_NAME → $BASE_BRANCH"
            echo "🚀 Creating new intelligent PR..."
            
            # Generate smart PR title and body
            COMMITS_COUNT=$(git rev-list --count origin/$BASE_BRANCH..$BRANCH_NAME 2>/dev/null || echo "1")
            LATEST_COMMIT_MSG=$(git log -1 --pretty=format:"%s" 2>/dev/null || echo "Copilot automated fix")
            
            PR_TITLE="🤖 DevUl Army Copilot Fix: $(echo "$LATEST_COMMIT_MSG" | head -c 50)..."
            PR_BODY="## 🤖 DevUl Army Automated Copilot Fix

**Branch:** \`$BRANCH_NAME\` → \`$BASE_BRANCH\`
**Commits:** $COMMITS_COUNT
**Created:** $(date -u)

### 📋 Summary
This PR was automatically created by DevUl Army Copilot to implement intelligent fixes and improvements.

### 🔍 Changes
$(git log --oneline origin/$BASE_BRANCH..$BRANCH_NAME --pretty=format:"- %s" 2>/dev/null || echo "- Automated improvements and fixes")

### 🧪 Testing
- [ ] Automated tests passing
- [ ] Manual verification completed
- [ ] No breaking changes introduced

### 🚀 Deployment
Ready for review and merge when validation is complete.


- This PR was created by the DevUl Army Copilot Idempotent PR Creation workflow_"

            # Create the PR
            NEW_PR_NUMBER=$(gh pr create \
              --title "$PR_TITLE" \
              --body "$PR_BODY" \
              --base "$BASE_BRANCH" \
              --head "$BRANCH_NAME" \
              --json number \
              --jq '.number')
            
            echo "✅ Created new PR #$NEW_PR_NUMBER: $BRANCH_NAME → $BASE_BRANCH"
          fi

      - name: Log PR operation summary
        if: always()
        run: |
          echo "📊 DevUl Army Copilot PR Management Summary:"
          echo "- Branch: ${{ github.ref_name }}"
          echo "- Target: main"
          echo "- Operation: Idempotent PR creation/update"
          echo "- Status: Complete"
          echo "🧠 Triggering memory system update..."
