name: PR scope gate

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  scope-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enforce precision scope
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "Title: $PR_TITLE"
          echo "Body length: ${#PR_BODY}"
          # Add your regex for allowed areas e.g. workflows|scripts|ai|app/src
          if ! git diff --name-only origin/${{ github.base_ref }}... | egrep -q '^(\\.github/workflows/|scripts/|configs/activation_rules.json|ai/|app/src/)'; then
            echo "PR touches out-of-scope files. Commenting and failing."
            echo "::error::Out-of-scope changes detected."
            exit 1
          fi
